name: video_player_web_hls
description: Web platform implementation of video_player and supports hls on chrome and other browsers.
homepage: https://github.com/balvinderz/video_player_web_hls
# 0.1.y+z is compatible with 1.0.0, if you land a breaking change bump
# the version to 2.0.0.
# See more details: https://github.com/flutter/flutter/wiki/Package-migration-to-1.0.0
version: 1.0.0+1
publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: VideoPlayerPluginHls
        fileName: video_player_web_hls.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^0.13.3
  video_player_platform_interface:
    git:
      url: https://github.com/WinTicket/plugins.git
      path: packages/video_player/video_player_platform_interface
      ref: 567c7bfc83a51a01a942a7a207fa5ef2dd74adb8
  js: ^0.6.3
dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.10.0"
